#!/bin/bash

set -ex

cd "${1}"

set +x

DIR=$(dirname "$0")

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $DIR/_base
source $DIR/_projects

PROJECTLIST=$(cat projects.json | jq -r .projects[].path | xargs)
VERSION="$(echo $PROJECTLIST | md5sum | cut -d ' ' -f 1)"
echo $VERSION | jq -R '.' | jq -s "map({md5: .})" >&3
